// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/nav-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderBar: typeof import('./src/components/slider-bar/index.vue')['default']
    SlotFooter: typeof import('./src/components/slot-footer/index.vue')['default']
    SlotIntro: typeof import('./src/components/slot-intro/index.vue')['default']
  }
}
